### PR TITLE
LPS-74837 CKEditor ignores table cellspacing

### PR DESCRIPTION
**Pull request by omarzzn3**
Hi Dustin,

I created this new PR containing the separate commits of my changes.

Best regards,
Omar

### CODE REVIEW

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Hi @omarzzn3,

Thanks for the new pull. Have you been able to successfully run the new tests you added? When I attempt to run them I get the errors shown below in the screenshot:

bendertests_style

**Comment by omarzzn3** [comment]
Hi Dustin,

Thank you for reviewing this.
I just reverified and I've got the errors also, but I don't see why they're occurring since I made the exact same changes made in the fix [here](https://github.com/ckeditor/ckeditor-dev/pull/622/files).
Added to that, they're related to the 'parse' property which is applied to the style attribute and claiming it as undefined. I'm working on the issue but it might be defined on another fix so, in this case, I'd have to find it and bring the definition also to our repo. 

Best regards,
Omar

**Comment by dustinryerson** [comment]
Sounds good, thanks for the information. I'll await your findings before merging this.

**Comment by omarzzn3** [comment]
Hi Dustin,

I was wondering if the failed tests were only in tests/core/config/style.js or also in other files.

Best regards,
Omar

**Comment by dustinryerson** [comment]
@omarzzn3 that's great to hear. For the tests related to the table plugin, the only other one that has some failures on my end is located at `/tests/plugins/table/table`. I'm not sure if it's related to your changes or not, but they seem somewhat related:

tests_plugins_table_table

**Comment by omarzzn3** [comment]
Hi Dustin,

Thank you for your response.

I figured out that the mentioned tests were failing and I already fixed
them

 [image: Images intégrées 1]

I will commit my changes to the pull request tomorrow morning.

Best regards,
Omar

2017-10-17 20:17 GMT+02:00 Dustin Ryerson <notifications@github.com>:

**Comment by omarzzn3** [comment]
Hi Dustin,

Thank you for your response.

I figured out that the mentioned tests were failing and I already fixed them 
tests passed

I will commit my changes to the pull request tomorrow morning. 

Best regards,
Omar

**Comment by omarzzn3** [comment]
Hi Dustin,

I just committed my changes for the broken tests.
Please let me know if you have any issues while reviewing this PR.

Best regards,
Omar

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
@omarzzn3 the table plugin tests are still showing the same error for me, can you double check it?

I'm still going to push this forward since it's been pending for a long time, but I'd like to ask you to send a follow up pull to fix the test if it's still broken (since there's a chance it's just broken on my system).

Thanks!

**Comment by omarzzn3** [comment]
Hi Dustin,

Thank you for your answer.
I think it may be related to your environment since all the tests passed in mine as you can see below:
tests_passed

Thanks again and best regards,
Omar

**Comment by dustinryerson** [comment]
@omarzzn3 on a second look, I'm not exactly sure how this fix is working...

The `CKEDITOR.tools.style.parse` namespace was only made available in CKEditor v.4.6.1 and newer, yet the `package.json` notes that the version of CKEditor used on the `ee-4.6.x` branch is v.4.6.0, implying that the parse namespace and helper functions would not yet be available for use.

Will you provide an explanation about how this is working?

**Comment by dustinryerson** [comment]
@omarzzn3 See https://github.com/ckeditor/ckeditor-dev/blob/release/4.6.x/core/tools.js#L1465-L1749, which does not exist in https://github.com/dustinryerson/liferay-ckeditor/blob/ee-4.6.x/core/tools.js

**Comment by omarzzn3** [comment]
hey @dustinryerson  sorry for this, I already made the changes on core/tools.js and added tests/tools/style.js but somehow I didn't push them to the PR branch.

I will push them right away if it's okay this way.
I'm sorry again for the inconvenience
Omar

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
