### PR TITLE
LPS-74837

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @dustinryerson,

Attached is an update for http://issues.liferay.com/browse/LPS-74837.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by omarzzn3** [comment]
Hi @dustinryerson,

Sorry for this late notification but I think my PR would need some changes.

After testing again my fix in order to create the hotfix,  I found that it's still not totally right, it fixed the **cellpadding** attribute but not the **cellspacing** and I found out this is caused by the border-collapse attribute inside the table class which is set to **collapse**. That value was introduced by clay according to the recent changes on master but also in the 6.2 we have the same value. The said attribute should be set to **separate** and I cannot proceed to change this value since it may affect many other components and obviously cause other regressions.

Thank you in advance for your help.
Best regards,
Omar

**Comment by jonmak08** [comment]
Closing pull request based on @omarzzn3's comments. 

@omarzzn3, can you resend an updated pull request with the changes to fix the **cellspacing** issue?

Please let me know if you have any questions. Thanks!

**Comment by omarzzn3** [comment]
Hi @jonmak08 ,

After finding the root cause explained previously, I would like to ask for your help on how to set the right value without affecting other depending components using the same attribute since.

Thank you in advance for your help,
Best regards,
Omar

**Comment by zsigmondrab** [comment]
ci:reopen

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by jonmak08** [comment]
Hey @omarzzn3,

I will take a look at this tomorrow and get back to you regarding what I can find.  Sorry for the delay.

**Comment by jonmak08** [comment]
Hey @omarzzn3,

We found that this issue actually comes from Bootstrap's CSS/Normalize CSS and is not anything custom to Liferay.  Normalize.css adds the line

```css
table {
    border-collapse: collapse;
}
```

You can see the issues listed:

* https://github.com/twbs/bootstrap/issues/12237
* https://github.com/necolas/normalize.css/issues/165
* https://github.com/jonathantneal/sanitize.css/issues/120
* https://github.com/necolas/normalize.css/issues/354
* https://github.com/necolas/normalize.css/issues/506

**Comment by omarzzn3** [comment]
Hi @jonmak08,

Thank you for taking care of this, I'm back from Amsterdam and I'll take it back.
Concerning the mentioned changes, they seem to be the right ones to solve this issue, I'll be waiting for @pat270 changes.

Thanks again and best regards,
Omar

**Comment by jonmak08** [comment]
Hey @omarzzn3,

Everything has already been sent to its respective branches/reviewers.  We are just waiting on everything to get pushed in.

Please let me know if you have any questions. Thanks!

**Comment by dustinryerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by omarzzn3** [comment]
Hi Everyone,

@jonmak08 would you please provide any pull request link or other refeence regarding the changes in bootstrap.css. 

@dustinryerson did you mean seperate SF changes from the new code or to sperate commits based on thechanges made in each file ? just to make sure I understand you correctly.

Thanks and best regards,
Omar

**Comment by dustinryerson** [comment]
@omarzzn3 I'd recommend separating commits based on what changes are being made rather than for each file.

For example:
1. LPS-12345 Fix table plugin because of `X`
2. LPS-12345 Add new tests
3. LPS-12345 Update existing tests
4. LPS-12345 Add package-lock.json

@jonmak08 should we be adding the package-lock.json file?

**Comment by jonmak08** [comment]
Hey guys,

The package-lock.json file is only for the npm dependencies to make sure you download all the correct versions.  It is not necessary unless you want to lock all the dependencies at a certain version.

**Comment by jonmak08** [comment]
Hey @omarzzn3,

The pull requests are:

master: https://github.com/dustinryerson/liferay-portal/pull/169
ee-7.0.x: https://github.com/liferay/liferay-portal-ee/pull/2695 and https://github.com/dustinryerson/liferay-portal-ee/pull/3060
ee-6.2.x: https://github.com/dustinryerson/liferay-portal-ee/pull/3061

Please let me know if you have any questions. Thanks!

**Comment by dustinryerson** [comment]
Forwarded: https://github.com/dustinryerson/liferay-ckeditor/pull/4

**Pull request closed without merging**
